export const GET_ALL_BLOG_REQUIRED = "GET_ALL_BLOG_REQUIRED"
export const  GET_ALL_BLOG_SUCCESS = "GET_ALL_BLOG_SUCCESS"
export const  GET_ALL_BLOG_FAIL = "GET_ALL_BLOG_FAIL"

export const GET_ONE_BLOG_REQUIRED = "GET_ONE_BLOG_REQUIRED"
export const  GET_ONE_BLOG_SUCCESS = "GET_ONE_BLOG_SUCCESS"
export const  GET_ONE_BLOG_FAIL = "GET_ONE_BLOG_FAIL"




