// GET ALL MOVIE
export const ALL_MOVIE_REQUEST = "ALL_MOVIE_REQUEST"
export const ALL_MOVIE_SUCCESS = "ALL_MOVIE_SUCCESS"
export const ALL_MOVIE_FAIL = "ALL_MOVIE_FAIL"

// GET ONE MOVIE ID

export const ONE_MOVIE_REQUEST = "ONE_MOVIE_REQUEST"
export const ONE_MOVIE_SUCCESS = "ONE_MOVIE_SUCCESS"
export const ONE_MOVIE_FAIL = "ONE_MOVIE_FAIL"