export const CREATE_RESERVATION_REQUEST = "CREATE_RESERVATION_REQUEST"
export const CREATE_RESERVATION_SUCCESS = "CREATE_RESERVATION_SUCCESS"
export const CREATE_RESERVATION_FAIL = "CREATE_RESERVATION_FAIL"